services:
  garnet:
    image: ghcr.io/microsoft/garnet:latest
    # image: yzy613/garnet:latest
    # image: altall/garnet:v1.0.0
    container_name: garnet
    command:
      --config-import-path /data/config/garnet.json
    restart: unless-stopped
    ports:
      - 3278:3278
    volumes:
      - ./garnet.json:/data/config/garnet.json
      - ./LogDir:/app/LogDir
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "6"
